# Turnos de trabajo por fecha ISO. Usa "Libranza" si no trabajas.
trabajo:
  "2025-11-05": "Libranza"
  "2025-11-06": "13:00 - 15:30"
  "2025-11-07": "13:30 - 22:00"
  "2025-11-08": "Libranza"
  "2025-11-09": "13:00 - 15:30"
  "2025-11-10": "Libranza"
  "2025-11-11": "Libranza"
  "2025-11-12": "13:00 - 15:30"
  "2025-11-13": "14:30 - 22:00"
  "2025-11-14": "13:30 - 16:00"
  "2025-11-15": "13:00 - 15:00"
  "2025-11-16": "14:00 - 19:00"